export interface KnowledgeResourceItem {
  id: string;
  titleTr: string;
  titleEn: string;
  url: string;
  descriptionTr?: string;
  descriptionEn?: string;
  badge?: string;
}

export interface KnowledgeCategory {
  id: string;
  icon: string;
  titleTr: string;
  titleEn: string;
  descriptionTr: string;
  descriptionEn: string;
  items: KnowledgeResourceItem[];
}

export const KNOWLEDGE_LIBRARY_CATEGORIES: KnowledgeCategory[] = [
  {
    id: 'official-erasmus',
    icon: '🇪🇺',
    titleTr: 'Resmi Erasmus+ Kaynakları',
    titleEn: 'Official Erasmus+ Resources',
    descriptionTr: 'Avrupa Komisyonu ve Ulusal Ajans resmi başvuru rehberleri, akreditasyon ve kalite standartları.',
    descriptionEn: 'Official European Commission and National Agency programme guides, accreditation and quality standards.',
    items: [
      {
        id: 'prog-guide',
        titleTr: 'Erasmus+ Program Rehberi (Güncel Çağrı)',
        titleEn: 'Erasmus+ Programme Guide',
        url: 'https://erasmus-plus.ec.europa.eu/programme-guide',
        descriptionTr: 'Resmi kurallar, uygunluk kriterleri ve bütçe kalemleri rehberi.',
        descriptionEn: 'Official rules, eligibility criteria and grant allocation framework.',
        badge: 'Official Guide',
      },
      {
        id: 'ua-gov',
        titleTr: 'Türkiye Ulusal Ajansı (Dışişleri Bakanlığı)',
        titleEn: 'Turkish National Agency',
        url: 'https://www.ua.gov.tr/',
        descriptionTr: 'Türkiye geneli çağrı takvimi, duyurular ve başvuru portali.',
        descriptionEn: 'National Agency portal for grant calls, calendar and application links.',
        badge: 'TR Agency',
      },
      {
        id: 'ka120-vet',
        titleTr: 'KA120-VET Mesleki Eğitim Akreditasyon Belgesi',
        titleEn: 'KA120-VET Accreditation',
        url: 'https://www.ua.gov.tr/programlar/firsatlar/ka120-vet-mesleki-egitim-ogrenici-ve-personel-hareketliligi-akreditasyon-belgesi/',
        descriptionTr: 'Akredite kurumlar için uzun vadeli stratejik hareketlilik planı rehberi.',
        descriptionEn: 'Accreditation framework for long-term institutional mobility planning.',
        badge: 'KA120',
      },
      {
        id: 'ka122-vet',
        titleTr: 'KA122-VET Kısa Süreli Hareketlilik Projeleri',
        titleEn: 'KA122-VET Short-Term Mobility Projects',
        url: 'https://www.ua.gov.tr/programlar/firsatlar/ka122-vet-mesleki-egitim-kisa-sureli-ogrenici-ve-personel-hareketliligi-projeleri/',
        descriptionTr: 'Akredite olmayan okullar için kısa dönemli hibe başvuru şartları.',
        descriptionEn: 'Short-term mobility grant application criteria for non-accredited VET schools.',
        badge: 'KA122',
      },
      {
        id: 'quality-standards',
        titleTr: 'Erasmus+ Hareketlilik Projeleri Kalite Standartları',
        titleEn: 'Erasmus+ Quality Standards for Mobility Projects',
        url: 'https://erasmus-plus.ec.europa.eu/resources/documents/erasmus-quality-standards-mobility-projects-vet-adults-schools_en',
        descriptionTr: 'Mesleki eğitimde kurumsal yönetim ve kapsayıcılık kalite ilkeleri.',
        descriptionEn: 'Key quality principles, management and inclusion criteria for VET mobilities.',
        badge: 'Standards',
      },
      {
        id: 'project-results-platform',
        titleTr: 'Erasmus+ Proje Sonuçları Platformu',
        titleEn: 'Erasmus+ Project Results Platform',
        url: 'https://erasmus-plus.ec.europa.eu/projects',
        descriptionTr: 'Avrupa genelinde finanse edilmiş projeler, iyi uygulamalar ve çıktılar.',
        descriptionEn: 'Official dissemination platform for completed projects and good practices.',
        badge: 'Database',
      },
    ],
  },
  {
    id: 'mobility-tools',
    icon: '📄',
    titleTr: 'Hareketlilik Belgeleri ve Araçları',
    titleEn: 'Mobility Documents and Tools',
    descriptionTr: 'Europass hareketlilik belgeleri, yönergeler, şablonlar ve Avrupa okul ağı araçları.',
    descriptionEn: 'Europass mobility documents, guidelines, templates and European school network platforms.',
    items: [
      {
        id: 'europass-mobility',
        titleTr: 'Europass Mobility (Hareketlilik Belgesi)',
        titleEn: 'Europass Mobility',
        url: 'https://europass.europa.eu/en/work-europe/mobility',
        descriptionTr: 'Yurtdışı staj ve eğitim kazanımlarını belgeleyen resmi AB standardı.',
        descriptionEn: 'Standard EU document recording knowledge and skills acquired abroad.',
        badge: 'Europass',
      },
      {
        id: 'europass-instructions',
        titleTr: 'Europass Mobility Kullanım Yönergeleri',
        titleEn: 'Europass Mobility Instructions',
        url: 'https://europass.europa.eu/en/document-library/europass-mobility-instructions-english',
        descriptionTr: 'Gönderici ve ev sahibi kuruluşlar için belge düzenleme kılavuzu.',
        descriptionEn: 'Step-by-step issuing instructions for sending and hosting bodies.',
        badge: 'Guide',
      },
      {
        id: 'europass-templates',
        titleTr: 'Europass Mobility Şablon ve Ek Belgeler',
        titleEn: 'Europass Mobility Template Documents',
        url: 'https://europass.europa.eu/en/europass-mobility-supplement-template-documents',
        descriptionTr: 'Resmi Word ve PDF şablon dosyaları, alan doldurma rehberleri.',
        descriptionEn: 'Official templates and supplement documentation files.',
        badge: 'Templates',
      },
      {
        id: 'eures',
        titleTr: 'EURES – Avrupa’da Yaşam ve Çalışma Koşulları',
        titleEn: 'EURES – Living and Working in Europe',
        url: 'https://eures.europa.eu/living-and-working_en',
        descriptionTr: 'AB ülkelerinde asgari ücretler, vergilendirme, barınma ve iş kanunları rehberi.',
        descriptionEn: 'Country-by-country labor market, living cost, accommodation and legal info.',
        badge: 'EURES',
      },
      {
        id: 'esep',
        titleTr: 'European School Education Platform (ESEP)',
        titleEn: 'European School Education Platform',
        url: 'https://school-education.ec.europa.eu/',
        descriptionTr: 'eTwinning, kurs ve okul ortaklıkları için Avrupa eğitim topluluğu.',
        descriptionEn: 'Unified hub for school education, eTwinning, courses and partner search.',
        badge: 'ESEP',
      },
    ],
  },
  {
    id: 'skills-occupations',
    icon: '🎯',
    titleTr: 'Beceriler, Yeterlilikler ve Meslekler',
    titleEn: 'Skills, Qualifications and Occupations',
    descriptionTr: 'Avrupa ESCO beceri taksonomisi ve EQF Avrupa Yeterlilik Çerçevesi seviyeleri.',
    descriptionEn: 'European ESCO skills taxonomy, occupation classifications, and EQF qualification framework.',
    items: [
      {
        id: 'esco-main',
        titleTr: 'ESCO – Avrupa Beceriler, Yetkinlikler ve Meslekler Portali',
        titleEn: 'ESCO – European Skills, Competences, Qualifications and Occupations',
        url: 'https://esco.ec.europa.eu/en',
        descriptionTr: '30 dilde 3.000+ meslek ve 13.800+ becerinin çok dilli sınıflandırması.',
        descriptionEn: 'Multilingual classification of 3,000+ occupations and 13,800+ skills.',
        badge: 'Taxonomy',
      },
      {
        id: 'esco-use',
        titleTr: 'ESCO Kullanım Kılavuzu & Entegrasyon',
        titleEn: 'Using ESCO',
        url: 'https://esco.ec.europa.eu/en/use-esco',
        descriptionTr: 'Müfredat ve öğrenme çıktılarında ESCO standartlarını kullanma rehberi.',
        descriptionEn: 'How to map learning outcomes and qualifications into ESCO.',
        badge: 'Integration',
      },
      {
        id: 'esco-classification',
        titleTr: 'ESCO Meslek ve Beceri Sınıflandırma Hiyerarşisi',
        titleEn: 'ESCO Classification and Occupations',
        url: 'https://esco.ec.europa.eu/en/classification',
        descriptionTr: 'Sektörel meslek ağaçları ve doğrudan bağlantılı temel yetkinlikler.',
        descriptionEn: 'Searchable occupational hierarchy and related skill clusters.',
        badge: 'Directory',
      },
      {
        id: 'eqf-levels',
        titleTr: 'Avrupa Yeterlilikler Çerçevesi (EQF 1–8 Düzeyleri)',
        titleEn: 'European Qualifications Framework (EQF)',
        url: 'https://europa.eu/europass/en/description-eight-eqf-levels',
        descriptionTr: 'Ulusal diplomaların AB genelinde kıyaslanmasını sağlayan 8 seviyeli matris.',
        descriptionEn: '8-level reference grid comparing national qualifications across the EU.',
        badge: 'EQF',
      },
    ],
  },
  {
    id: 'vet-knowledge',
    icon: '🏛️',
    titleTr: 'Mesleki Eğitim Politikaları ve Araştırmalar',
    titleEn: 'VET Knowledge and Policy',
    descriptionTr: 'CEDEFOP ve ETF mesleki eğitim sistemleri araştırmaları, sınır ötesi yeterlilikler ve EPALE.',
    descriptionEn: 'CEDEFOP and ETF policy studies, cross-border qualifications, and EPALE adult learning.',
    items: [
      {
        id: 'cedefop-main',
        titleTr: 'CEDEFOP – Mesleki Eğitimi Geliştirme Avrupa Merkezi',
        titleEn: 'CEDEFOP – Vocational Education and Training',
        url: 'https://www.cedefop.europa.eu/en',
        descriptionTr: 'Avrupa mesleki eğitim ve çıraklık politikalarının temel araştırma ajansı.',
        descriptionEn: 'European Centre for the Development of Vocational Training.',
        badge: 'EU Agency',
      },
      {
        id: 'cedefop-policies',
        titleTr: 'CEDEFOP – Mesleki Eğitim Politikaları ve Sistemleri',
        titleEn: 'CEDEFOP – VET Policies and Systems',
        url: 'https://www.cedefop.europa.eu/en/themes/vet-policies-and-systems',
        descriptionTr: 'Üye ülkelerin mesleki eğitim reformları, ikili eğitim ve finansman modelleri.',
        descriptionEn: 'Country comparative reports on apprenticeship and VET structures.',
        badge: 'Policy',
      },
      {
        id: 'cedefop-qualifications',
        titleTr: 'CEDEFOP – Sınır Ötesi Yeterlilikler & Hareketlilik',
        titleEn: 'CEDEFOP – VET Qualifications Across Borders',
        url: 'https://www.cedefop.europa.eu/en/themes/vet-qualifications-across-borders',
        descriptionTr: 'Öğrenici hareketliliğinde mesleki diplomaların karşılıklı tanınması.',
        descriptionEn: 'Recognition of learning outcomes and qualification portability.',
        badge: 'Mobility',
      },
      {
        id: 'cedefop-publications',
        titleTr: 'CEDEFOP Yayınları ve Sektörel Raporlar',
        titleEn: 'CEDEFOP Publications and Reports',
        url: 'https://www.cedefop.europa.eu/en/publications',
        descriptionTr: 'Geleceğin becerileri, yeşil ve dijital dönüşüm VET etki analizleri.',
        descriptionEn: 'Future skills forecasts, green/digital transition reports.',
        badge: 'Reports',
      },
      {
        id: 'etf-main',
        titleTr: 'European Training Foundation (ETF)',
        titleEn: 'European Training Foundation',
        url: 'https://www.etf.europa.eu/en',
        descriptionTr: 'AB komşuluk ülkeleri ve aday ülkeler için mesleki beceri geliştirme vakfı.',
        descriptionEn: 'EU agency supporting education and skills development in partner countries.',
        badge: 'ETF',
      },
      {
        id: 'etf-resources',
        titleTr: 'ETF Yayınları ve Kurumsal Kaynaklar',
        titleEn: 'ETF Publications and Resources',
        url: 'https://www.etf.europa.eu/en/publications-and-resources',
        descriptionTr: 'Beceri açığı, işgücü piyasası analizleri ve yönetişim raporları.',
        descriptionEn: 'Country reviews, governance and policy briefs.',
        badge: 'Resources',
      },
      {
        id: 'epale',
        titleTr: 'EPALE – Elektronik Yetişkin Eğitimi Platformu',
        titleEn: 'EPALE – European Adult Learning Platform',
        url: 'https://epale.ec.europa.eu/en',
        descriptionTr: 'Mesleki eğitim eğiticileri, hayat boyu öğrenme ve ortak bulma ağı.',
        descriptionEn: 'Community of adult educators, VET teachers and project partners.',
        badge: 'EPALE',
      },
    ],
  },
  {
    id: 'quality-assurance',
    icon: '🛡️',
    titleTr: 'Kalite Güvencesi (EQAVET)',
    titleEn: 'Quality Assurance (EQAVET)',
    descriptionTr: 'Avrupa Mesleki Eğitim Kalite Güvencesi Referans Çerçevesi döngüsü ve kılavuzları.',
    descriptionEn: 'European Quality Assurance in VET reference framework cycle, tools and library.',
    items: [
      {
        id: 'eqavet-main',
        titleTr: 'EQAVET – Avrupa Mesleki Eğitimde Kalite Güvencesi',
        titleEn: 'EQAVET – European Quality Assurance in VET',
        url: 'https://employment-social-affairs.ec.europa.eu/policies-and-activities/skills-and-qualifications/working-together/eqavet-european-quality-assurance-vocational-education-and-training_en',
        descriptionTr: 'Mesleki eğitimin etkililiğini ölçen resmi Avrupa referans çerçevesi.',
        descriptionEn: 'EU reference framework for quality assurance in vocational education.',
        badge: 'Framework',
      },
      {
        id: 'eqavet-cycle',
        titleTr: 'EQAVET Kalite Güvencesi Döngüsü (Plan-Do-Check-Act)',
        titleEn: 'EQAVET Quality Assurance Cycle',
        url: 'https://employment-social-affairs.ec.europa.eu/policies-and-activities/skills-and-qualifications/working-together/eqavet-european-quality-assurance-vocational-education-and-training/about-eqavet/eqavet-quality-assurance-cycle_en',
        descriptionTr: 'Planlama, uygulama, değerlendirme ve gözden geçirme adımları.',
        descriptionEn: 'Four-stage PDCA quality cycle methodology for institutions.',
        badge: 'Cycle',
      },
      {
        id: 'eqavet-provider',
        titleTr: 'Okul ve Kurum Düzeyinde EQAVET Standartları',
        titleEn: 'EQAVET at Provider Level',
        url: 'https://employment-social-affairs.ec.europa.eu/policies-and-activities/skills-and-qualifications/working-together/eqavet-european-quality-assurance-vocational-education-and-training/about-eqavet/eqavet-vet-provider-level_en',
        descriptionTr: 'Meslek liseleri için iç kalite değerlendirmesi ve geri bildirim sistemleri.',
        descriptionEn: 'Practical self-assessment and feedback mechanisms for schools.',
        badge: 'Provider',
      },
      {
        id: 'eqavet-library',
        titleTr: 'EQAVET Sanal Kütüphanesi & Araç Seti',
        titleEn: 'EQAVET Virtual Library',
        url: 'https://employment-social-affairs.ec.europa.eu/policies-and-activities/skills-and-qualifications/working-together/eqavet-european-quality-assurance-vocational-education-and-training/virtual-library_en',
        descriptionTr: 'Kalite göstergeleri kılavuzu, vaka analizleri ve değerlendirme araçları.',
        descriptionEn: 'Indicators handbook, case studies and peer-review guidelines.',
        badge: 'Virtual Library',
      },
    ],
  },
  {
    id: 'project-examples',
    icon: '💡',
    titleTr: 'Proje Örnekleri ve İyi Uygulamalar',
    titleEn: 'Project Examples & Results',
    descriptionTr: 'Başarılı Erasmus+ hareketlilik projeleri, yaygınlaştırma ve emsal örnek veri tabanı.',
    descriptionEn: 'Completed Erasmus+ mobility project archives, good practice examples and outcomes.',
    items: [
      {
        id: 'proj-results',
        titleTr: 'Erasmus+ Proje Çıktıları & Örnek Projeler',
        titleEn: 'Erasmus+ Project Results',
        url: 'https://erasmus-plus.ec.europa.eu/projects',
        descriptionTr: 'Ülke, konu ve sektör bazında filtrelenebilir resmi proje arşivi.',
        descriptionEn: 'Official searchable database of all EU funded Erasmus+ projects.',
        badge: 'Results',
      },
      {
        id: 'proj-results-about',
        titleTr: 'Proje Sonuçları Platformunun Amacı & Kullanımı',
        titleEn: 'About the Project Results Platform',
        url: 'https://erasmus-plus.ec.europa.eu/what-is-the-purpose-of-the-erasmus-project-results-platform',
        descriptionTr: 'Platformun işlevi, hibe yararlanıcılarının yükümlülükleri ve etki ölçümü.',
        descriptionEn: 'Dissemination rules, beneficiary publishing duties and transparency.',
        badge: 'Info',
      },
      {
        id: 'proj-results-faq',
        titleTr: 'Proje Sonuçları Platformu Sık Sorulan Sorular (SSS)',
        titleEn: 'Project Results Platform FAQ',
        url: 'https://erasmus-plus.ec.europa.eu/projects/frequently-asked-questions',
        descriptionTr: 'Nihai raporlama, çıktı yükleme ve kamuya açılma süreçleri kılavuzu.',
        descriptionEn: 'Frequently asked questions regarding reporting and publishing.',
        badge: 'FAQ',
      },
    ],
  },
  {
    id: 'turkiye-vet',
    icon: '🇹🇷',
    titleTr: 'Türkiye Mesleki Eğitim ve Sektörel Kaynaklar',
    titleEn: 'Türkiye VET and Industry Resources',
    descriptionTr: 'MEB Mesleki Eğitim Genel Müdürlüğü, Mesleki Yeterlilik Kurumu, İŞKUR, TOBB ve OSBÜK.',
    descriptionEn: 'Ministry of National Education VET, VQA (MYK), İŞKUR, TOBB and OSBÜK industry networks.',
    items: [
      {
        id: 'mtegm',
        titleTr: 'MEB Mesleki ve Teknik Eğitim Genel Müdürlüğü (MTEGM)',
        titleEn: 'Ministry of National Education – VET (MTEGM)',
        url: 'https://mtegm.meb.gov.tr/',
        descriptionTr: 'Türkiye genelindeki MTAL, ÇPAL, MESEM müfredatları ve sektör işbirlikleri.',
        descriptionEn: 'Turkish official VET curriculum, school directories and sector protocols.',
        badge: 'MEB',
      },
      {
        id: 'myk',
        titleTr: 'Mesleki Yeterlilik Kurumu (MYK)',
        titleEn: 'Vocational Qualifications Authority (MYK)',
        url: 'https://www.myk.gov.tr/',
        descriptionTr: 'Ulusal meslek standartları, Europass Türkiye ve sınav belgelendirme merkezi.',
        descriptionEn: 'National occupational standards and Europass National Center.',
        badge: 'MYK',
      },
      {
        id: 'iskur',
        titleTr: 'Türkiye İş Kurumu (İŞKUR)',
        titleEn: 'Turkish Employment Agency (İŞKUR)',
        url: 'https://www.iskur.gov.tr/',
        descriptionTr: 'İşgücü piyasası talep araştırmaları, staj programları ve mesleki eğitim kursları.',
        descriptionEn: 'Labor market demand analyses, internships and employment programs.',
        badge: 'İŞKUR',
      },
      {
        id: 'tobb',
        titleTr: 'Türkiye Odalar ve Borsalar Birliği (TOBB)',
        titleEn: 'Union of Chambers and Commodity Exchanges of Türkiye (TOBB)',
        url: 'https://www.tobb.org.tr/',
        descriptionTr: '81 il ticaret ve sanayi odaları, mesleki eğitim protokolleri ve özel sektör ağı.',
        descriptionEn: 'National umbrella organization of trade and industry chambers.',
        badge: 'TOBB',
      },
      {
        id: 'osbuk',
        titleTr: 'Organize Sanayi Bölgeleri Üst Kuruluşu (OSBÜK)',
        titleEn: 'Supreme Organisation of Organised Industrial Zones (OSBÜK)',
        url: 'https://www.osbuk.org/',
        descriptionTr: 'Sanayi bölgeleri içindeki meslek liseleri, staj kotaları ve teknik altyapı.',
        descriptionEn: 'National association of organized industrial zones and technical centers.',
        badge: 'OSBÜK',
      },
    ],
  },
];
