/**
 * ErasmusMobility - KA122 Official Form Structure & Guidance Schema
 * Kısa Dönemli Öğrenici ve Personel Hareketliliği Projeleri (KA122-VET)
 *
 * KA121'den temel farkı:
 * KA121 yalnızca akredite kurumlara yönelik bütçe talep formuyken;
 * KA122 tam teşekküllü, 100 puan üzerinden yarışmalı bir PROJE BAŞVURUSUDUR.
 * Bu nedenle Background, Objectives, Quality Standards ve Follow-up bölümlerinde
 * yoğun AI metin desteği (AI-Assisted) gerektirir.
 */

import { KA121FillStrategy, KA121FieldGuidance, KA121FormField, KA121FormSection } from './ka121-form-schema';

export type KA122FillStrategy = KA121FillStrategy;
export type KA122FieldGuidance = KA121FieldGuidance;
export type KA122FormField = KA121FormField;
export type KA122FormSection = KA121FormSection;

export interface KA122FormSchema {
  formId: 'KA122-VET' | 'KA122-SCH' | 'KA122-ADU';
  title: string;
  version: string;
  tableOfContents: Array<{
    id: string;
    title: string;
    page: number;
    subitems?: Array<{ id: string; title: string; page: number }>;
  }>;
  sections: KA122FormSection[];
}

/**
 * Resmi KA122 Form İskeleti (Table of Contents)
 */
export const OFFICIAL_KA122_SCHEMA: KA122FormSchema = {
  formId: 'KA122-VET',
  title: 'Short-term projects for mobility of learners and staff in vocational education and training (KA122-VET)',
  version: '2024-2027 Official Standard',
  tableOfContents: [
    { id: 'context', title: 'Context', page: 3 },
    { id: 'project-summary', title: 'Project summary', page: 4 },
    { id: 'applicant-organisation-summary', title: 'Applicant organisation', page: 5 },
    {
      id: 'participating-organisations',
      title: 'Participating organisations',
      page: 6,
      subitems: [{ id: 'applicant-organisation-details', title: 'Applicant organisation', page: 6 }],
    },
    { id: 'background', title: 'Background', page: 7 },
    { id: 'project-objectives', title: 'Project objectives', page: 8 },
    { id: 'activities', title: 'Activities', page: 9 },
    {
      id: 'budget',
      title: 'Budget',
      page: 10,
      subitems: [
        { id: 'organisational-support', title: 'Organisational support', page: 11 },
        { id: 'inclusion-support', title: 'Inclusion support', page: 12 },
        { id: 'exceptional-costs', title: 'Exceptional costs', page: 13 },
      ],
    },
    { id: 'quality-standards', title: 'Quality standards', page: 14 },
    { id: 'follow-up', title: 'Follow-up', page: 17 },
    { id: 'annexes', title: 'Annexes', page: 18 },
    { id: 'application-conditions', title: 'Application conditions', page: 19 },
    { id: 'submission-history', title: 'Submission history', page: 21 },
  ],
  sections: [
    {
      id: 'context',
      pageNumber: 3,
      title: 'Context',
      description: 'Proje temel bilgileri: Sektör alanı, proje başlığı (Türkçe & İngilizce), başlangıç/bitiş tarihleri, süre ve Ulusal Ajans seçimi.',
      fields: [
        {
          id: 'ctx_field_of_application',
          fieldCode: 'Field of application',
          label: 'Field of application',
          description: 'Başvuru yapılan eğitim alanı (Mesleki Eğitim için Vocational Education and Training).',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true, allowedValues: ['Vocational Education and Training'] },
          guidance: {
            school: 'Mesleki eğitim kurumları (Meslek Liseleri, MEM vb.) için bu alan sabit "Vocational Education and Training" olmalıdır.',
            host: 'Ev sahibi kurumun sunduğu eğitim veya staj programı bu sektöre uygun olmalıdır.',
          },
        },
        {
          id: 'ctx_project_title',
          fieldCode: 'Project title',
          label: 'Project title',
          description: 'Projenin ulusal dildeki (Türkçe) resmi başlığı.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 10, maxChars: 250 },
          guidance: {
            school: 'Projenin mesleki odağını, hedef kitlesini ve kazanılacak vizyonu net özetleyen etkileyici bir başlık belirleyin.',
            host: 'Başlıkta host kurumla yapılacak staj alanı (örn: CNC, Yenilenebilir Enerji, Robotik) yansıtılabilir.',
            aiPromptTemplate: 'Mesleki alan: {vetField}. Temel beceri açığı: {skillGap}. Hareketlilik hedefi: {mobilityGoal}. Değerlendiricileri etkileyecek, Erasmus ruhuna uygun 3 farklı yaratıcı Türkçe proje başlığı öner.',
          },
        },
        {
          id: 'ctx_project_title_en',
          fieldCode: 'Project title in English',
          label: 'Project title in English',
          description: 'Projenin resmi İngilizce başlığı (Avrupa Komisyonu veri tabanında yer alacak küresel başlık).',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 10, maxChars: 250 },
          guidance: {
            school: 'Türkçe başlığın uluslararası platformlarda ve Proje Sonuçları Platformunda (EPRP) sergilenecek profesyonel İngilizce karşılığıdır.',
            host: 'Ev sahibi kurum projeyi bu İngilizce başlıkla tanıyacak ve sertifikalara bu başlığı yazacaktır.',
            aiPromptTemplate: 'Türkçe proje başlığı: "{projectTitle}". Bunu profesyonel, akıcı ve Erasmus terminolojisine uygun İngilizceye çevir.',
          },
        },
        {
          id: 'ctx_start_date',
          fieldCode: 'Project start date (dd/mm/yyyy)',
          label: 'Project start date',
          description: 'Proje başlangıç tarihi (Genellikle çağrı yılı 1 Haziran ile 31 Aralık arasında seçilmelidir; varsayılan: 01/06/2026).',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: {
            school: 'Tarih seçerken hazırlık, katılımcı seçimi ve pasaport/vize süreçleri için en az 3-4 ay ön hazırlık payı bırakın. Eylül-Ekim gibi başlatmak okullar için genelde daha pratiktir.',
            host: 'Hareketliliğin yapılacağı mevsimin ve işletmelerin stajyer kabul takviminin bu tarihe uygunluğunu teyit edin.',
          },
        },
        {
          id: 'ctx_duration',
          fieldCode: 'Project duration',
          label: 'Project duration (in months)',
          description: 'Proje toplam süresi (KA122 kurallarına göre 6 ay ile 18 ay arasında olmalıdır; en yaygın: 12 veya 15 ay).',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true, allowedValues: ['6', '12', '15', '18'] },
          guidance: {
            school: 'KA122 için maksimum süre 18 aydır. 12 veya 15 ay seçmek; hazırlık, gidiş, dönüş ve yaygınlaştırma faaliyetleri için en dengeli süredir.',
            host: 'Host kurumla hareketlilik tarihleri bu süre zarfında netleştirilecektir.',
          },
        },
        {
          id: 'ctx_end_date',
          fieldCode: 'Project end date (dd/mm/yyyy)',
          label: 'Project end date',
          description: 'Proje bitiş tarihi (Başlangıç tarihi + süre formülüyle otomatik üretilir).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Sistem başlangıç tarihi ve süreye göre otomatik hesaplar.',
            host: 'Tüm hareketlilikler, Europass düzenlemeleri ve nihai raporlama bu tarihten önce tamamlanmalıdır.',
          },
        },
        {
          id: 'ctx_national_agency',
          fieldCode: 'National agency of the applicant organisation',
          label: 'National agency of the applicant organisation',
          description: 'Başvuran kurumun bağlı olduğu Ulusal Ajans (Örn: TR01 - Türkiye Ulusal Ajansı).',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: {
            school: 'Kurumunuzun bulunduğu ülkeye göre sistem otomatik atar.',
            host: 'Başvuru bu ulusal ajansın belirlediği hibe ve kurallara göre incelenir.',
          },
        },
        {
          id: 'ctx_form_language',
          fieldCode: 'Language used to fill in the form',
          label: 'Language used to fill in the form',
          description: 'Formun doldurulduğu dil.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true, allowedValues: ['Turkish', 'English'] },
          guidance: {
            school: 'Türkiye Ulusal Ajansı için Türkçe veya İngilizce doldurulabilir. Türkçe yazılsa bile Project Summary ve başlık İngilizce olmak zorundadır.',
            host: 'Host ortaklarla paylaşılacak form özeti ve öğrenme anlaşmaları için İngilizce içerik şarttır.',
          },
        },
        {
          id: 'ctx_participation_limit_rule',
          fieldCode: 'Rules on number of participations',
          label: '5-Year Maximum 3 Grants Rule',
          description: 'Resmi Kural: Bir kurum 5 ardışık çağrı yılı içinde aynı alanda (VET) en fazla 3 kez KA122 hibesi alabilir. Daha fazlası için akreditasyona (KA120) başvurulmalıdır.',
          fillStrategy: 'SYSTEM_GENERATED',
          sourceKey: 'organisation.pastKa122GrantsCount',
          rules: { isMandatory: true },
          guidance: {
            school: '⚠️ ÇOK ÖNEMLİ KURAL: Kurumunuz son 5 yılda 3 kez KA122-VET hibesi aldıysa bu başvuru reddedilir! Sistemimiz bunu Eligibility motoruyla otomatik denetler ve gerekirse sizi KA120 Akreditasyonuna yönlendirir.',
            host: 'Okulun bu kotayı aşmadığından emin olmak projenin iptal riskini ortadan kaldırır.',
          },
        },
      ],
    },
    {
      id: 'project-summary',
      pageNumber: 4,
      title: 'Project summary',
      description: 'Projenin arka planı, hedefleri ve beklenen sonuçları. Proje kabul edilirse Avrupa Komisyonu ve Ulusal Ajans tarafından halka açık olarak yayınlanacaktır.',
      fields: [
        {
          id: 'sum_background',
          fieldCode: 'i. Background: Why did you apply for this project?',
          label: 'Background (Ulusal Dil / Türkçe)',
          description: 'Neden bu projeye başvurdunuz? Kurumunuzun durumu, mesleki ihtiyaçlar ve hareketlilik gerekçesi.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2000 },
          guidance: {
            school: 'Okulunuzun mesleki profili, öğrencilerin karşılaştığı teknik/istihdam açıkları ve neden AB düzeyinde bir staj projesine ihtiyaç duyulduğu açıkça yazılmalıdır.',
            host: 'Host kurumun sunduğu ileri teknolojiler ve staj ortamının okulun bu açığını nasıl kapatacağı vurgulanmalıdır.',
            aiPromptTemplate: 'Okul adı: {schoolName}, Şehir: {city}, Mesleki alan: {vetField}. İhtiyaç duyulan temel yeterlilik açığı: {primaryGap}. Neden bu projeye başvurulduğunu anlatan, resmi değerlendirme ölçütlerine uygun güçlü bir arka plan özeti hazırla.',
          },
        },
        {
          id: 'sum_background_en',
          fieldCode: 'Background translation in English',
          label: 'Background (English Translation)',
          description: 'Arka plan özetinin resmi İngilizce çevirisi (Zorunludur).',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2000 },
          guidance: {
            school: 'Türkçe metin oluşturulduktan sonra tek tıkla yapay zeka ile profesyonel İngilizceye çevrilir.',
            host: 'Proje özeti host kurum tarafından kurumsal portföylerinde referans olarak kullanılabilir.',
            aiPromptTemplate: 'Aşağıdaki proje arka plan metnini Erasmus+ terminolojisine uygun olarak akıcı ve profesyonel bir İngilizceye çevir:\n\n"{sum_background}"',
          },
        },
        {
          id: 'sum_objectives',
          fieldCode: 'ii. Objectives: What do you want to achieve by implementing the project?',
          label: 'Objectives (Ulusal Dil / Türkçe)',
          description: 'Projeyi uygulayarak neyi başarmak istiyorsunuz? Somut hedefler.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2000 },
          guidance: {
            school: 'Hedefler genel temenniler değil, ölçülebilir ve somut olmalıdır (Örn: Öğrencilerin sektör standardı CNC tezgahlarında pratik beceri kazanması, Europass alması, yabancı dil özgüveni kazanması).',
            host: 'Staj sonunda öğrencilere kazandırılacak somut teknik çıktılar (technical outcomes) bu hedeflere doğrudan yansıtılmalıdır.',
            aiPromptTemplate: 'Hedeflenen teknik çıktılar: {technicalOutcome}, Transversal (yumuşak) beceriler: {transversalOutcome}. Bu çıktılara dayalı net, ölçülebilir proje hedefleri paragrafı oluştur.',
          },
        },
        {
          id: 'sum_objectives_en',
          fieldCode: 'Objectives translation in English',
          label: 'Objectives (English Translation)',
          description: 'Hedefler özetinin resmi İngilizce çevirisi (Zorunludur).',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2000 },
          guidance: {
            school: 'Yapay zeka ile anında İngilizceye çevrilir.',
            host: 'Host kurumun hedefleri net görmesi sağlanır.',
            aiPromptTemplate: 'Aşağıdaki proje hedefleri metnini profesyonel İngilizceye çevir:\n\n"{sum_objectives}"',
          },
        },
        {
          id: 'sum_results',
          fieldCode: 'iii. Results: What results do you expect your project to have?',
          label: 'Results (Ulusal Dil / Türkçe)',
          description: 'Projenizin hangi somut sonuçları doğurmasını bekliyorsunuz? (Katılımcı, kurum ve yerel sektör düzeyinde etki).',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2000 },
          guidance: {
            school: 'Hem öğrenci düzeyinde (staj tamamlama, istihdam edilebilirlik, dil gelişimi), hem okul düzeyinde (müfredatın güncellenmesi, uluslararasılaşma) beklenen somut sonuçları listeleyin.',
            host: 'Host kurumla kurulan uzun vadeli ortaklık ve gelecekteki olası işbirlikleri bir kurumsal sonuç olarak belirtilebilir.',
            aiPromptTemplate: 'Katılımcı sayısı: {participantCount}, Faaliyet: {mobilityGoal}. Katılımcıların ve okulun elde edeceği somut, ölçülebilir kazanımları ve etki sonuçlarını değerlendiriciyi etkileyecek dilde özetle.',
          },
        },
        {
          id: 'sum_results_en',
          fieldCode: 'Results translation in English',
          label: 'Results (English Translation)',
          description: 'Beklenen sonuçlar özetinin resmi İngilizce çevirisi (Zorunludur).',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2000 },
          guidance: {
            school: 'Yapay zeka ile anında İngilizceye çevrilir.',
            host: 'İşlem gerekmez.',
            aiPromptTemplate: 'Aşağıdaki beklenen sonuçlar metnini profesyonel İngilizceye çevir:\n\n"{sum_results}"',
          },
        },
      ],
    },
    {
      id: 'applicant-organisation-summary',
      pageNumber: 5,
      title: 'Applicant organisation',
      description: 'Başvuran kurumun kurumsal kimlik tablosu.',
      fields: [
        {
          id: 'app_sum_oid',
          fieldCode: 'OID',
          label: 'Organisation ID (OID)',
          description: 'Kurumun resmi Avrupa Komisyonu OID kodu.',
          fillStrategy: 'DIRECT_AUTOFILL',
          sourceKey: 'organisation.oid',
          rules: { isMandatory: true },
          guidance: { school: 'Sistem okul profilinizden otomatik çeker.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'app_sum_legal_name',
          fieldCode: 'Legal name',
          label: 'Legal name',
          description: 'Kurumun resmi adı.',
          fillStrategy: 'DIRECT_AUTOFILL',
          sourceKey: 'organisation.name',
          rules: { isMandatory: true },
          guidance: { school: 'Otomatik çekilir.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'app_sum_country',
          fieldCode: 'Country',
          label: 'Country',
          description: 'Kurumun ülkesi.',
          fillStrategy: 'DIRECT_AUTOFILL',
          sourceKey: 'organisation.countryCode',
          rules: { isMandatory: true },
          guidance: { school: 'Otomatik çekilir.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'app_sum_region',
          fieldCode: 'Region',
          label: 'Region',
          description: 'Kurumun bulunduğu resmi NUTS-2 bölgesi veya ili.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: { school: 'Şehir/ilçe verinize göre atanır.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'app_sum_city',
          fieldCode: 'City',
          label: 'City',
          description: 'Kurumun bulunduğu şehir.',
          fillStrategy: 'DIRECT_AUTOFILL',
          sourceKey: 'organisation.city',
          rules: { isMandatory: true },
          guidance: { school: 'Otomatik çekilir.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'app_sum_website',
          fieldCode: 'Website',
          label: 'Website',
          description: 'Kurumun resmi web sitesi adresi.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: { school: 'Okulun web sitesi (Örn: meb.k12.tr adresi).', host: 'İşlem gerekmez.' },
        },
      ],
    },
    {
      id: 'participating-organisations',
      pageNumber: 6,
      title: 'Participating organisations',
      description: 'Başvuran kurum ve destekleyen kuruluş detayları.',
      fields: [],
      subsections: [
        {
          id: 'applicant-organisation-details',
          pageNumber: 6,
          title: 'Applicant organisation',
          description: 'Yasal temsilci, iletişim kişisi ve destekleyen kuruluş beyanı.',
          fields: [
            {
              id: 'app_det_oid',
              fieldCode: 'Organisation ID',
              label: 'Organisation ID',
              fillStrategy: 'DIRECT_AUTOFILL',
              sourceKey: 'organisation.oid',
              rules: { isMandatory: true },
              guidance: { school: 'Kurum OID numarası.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'app_det_legal_name',
              fieldCode: 'Legal name',
              label: 'Legal name',
              fillStrategy: 'DIRECT_AUTOFILL',
              sourceKey: 'organisation.name',
              rules: { isMandatory: true },
              guidance: { school: 'Kurumun resmi yasal adı.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'app_det_country',
              fieldCode: 'Country',
              label: 'Country',
              fillStrategy: 'DIRECT_AUTOFILL',
              sourceKey: 'organisation.countryCode',
              rules: { isMandatory: true },
              guidance: { school: 'Kurumun ülkesi.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'app_det_city',
              fieldCode: 'City',
              label: 'City',
              fillStrategy: 'DIRECT_AUTOFILL',
              sourceKey: 'organisation.city',
              rules: { isMandatory: true },
              guidance: { school: 'Kurumun şehri.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'app_det_supporting_org_question',
              fieldCode: 'Supporting organisations question',
              label: 'My organisation plans to work with other supporting organisations that are not going to host our participants, but are going to help with the implementation of activities.',
              description: 'Öğrenci/personeli ağırlamayıp sadece proje idari işlerine destek veren harici aracı kuruluş kullanımı.',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true, allowedValues: ['Yes', 'No'] },
              guidance: {
                school: '⚠️ KRİTİK REHBERLİK: Ev sahibi (Host) kurumlar staj eğitimi ve mentorluk sağladıkları için "Supporting Organisation" SAYILMAZLAR! Bu soruya "No" denilmelidir. Sadece proje yazımı/yönetimi için ticari bir danışmanlık firmasına yetki devrediliyorsa "Yes" seçilir (ki bu da değerlendiriciler nezdinde kurumsal kapasite zayıflığı olarak algılanabilir).',
                host: 'Öğrencilere staj ve mentörlük veren host kurumlar resmi kalite standartlarında doğrudan ev sahibi ortaktır, supporting organisation değildir. "No" seçeneği host ile çalışmaya engel değildir.',
              },
            },
          ],
        },
      ],
    },
    {
      id: 'background',
      pageNumber: 7,
      title: 'Background & Past participation',
      description: 'Kurumun yapısı, faaliyetleri, öğrenci profili (kapsayıcılık), personel sayıları ve geçmiş Erasmus+ katılım kayıtları (30 Puanlık Uygunluk / Relevance değerlendirmesinin temeli).',
      fields: [
        {
          id: 'bg_is_public_body',
          fieldCode: 'Is the organisation a public body?',
          label: 'Is the organisation a public body?',
          description: 'Kurumun kamu kurumu olup olmadığı (Kamu okulları için Yes).',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true, allowedValues: ['Yes', 'No'] },
          guidance: { school: 'OID kaydından otomatik gelir. Devlet okulları ve MEM için "Yes".', host: 'İşlem gerekmez.' },
        },
        {
          id: 'bg_is_non_profit',
          fieldCode: 'Is the organisation a non-profit?',
          label: 'Is the organisation a non-profit?',
          description: 'Kurumun kar amacı gütmeyen kuruluş olup olmadığı.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true, allowedValues: ['Yes', 'No'] },
          guidance: { school: 'OID kaydından otomatik gelir. Okullar için "Yes".', host: 'İşlem gerekmez.' },
        },
        {
          id: 'bg_type_of_org',
          fieldCode: 'Type of organisation',
          label: 'Type of organisation',
          description: 'Kurumu en iyi tanımlayan kuruluş türü.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true, allowedValues: ['Vocational education and training school/centre', 'General education school', 'Local/Regional authority'] },
          guidance: { school: 'Meslek liseleri için "Vocational education and training school/centre" seçilir.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'bg_provides_learning_programmes',
          fieldCode: 'Does your organisation provide any formal or informal learning programmes relevant for this application?',
          label: 'Does your organisation provide any formal or informal learning programmes relevant for this application?',
          description: 'Kurumun bu başvuru ile ilgili örgün veya yaygın eğitim programı verip vermediği.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true, allowedValues: ['Yes', 'No'] },
          guidance: { school: 'Meslek okulları örgün mesleki eğitim verdiği için kesinlikle "Yes" olmalıdır.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'bg_main_activities',
          fieldCode: 'i. What are your organisation\'s main activities?',
          label: 'Main activities of the organisation',
          description: 'Kurumunuzun ana faaliyet alanları, eğitim kolları ve kurumsal misyonu.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2500 },
          guidance: {
            school: 'Okulunuzun tarihi, kaç alanda mesleki eğitim verdiği, yerel sanayi ile işbirlikleri ve temel başarıları anlatılmalıdır.',
            host: 'Bilgi amaçlıdır.',
            aiPromptTemplate: 'Okul adı: {schoolName}, Şehir: {city}, Mevcut mesleki alanlar: {vetField}. Kurumun ana faaliyetlerini, bölgedeki konumunu ve eğitim misyonunu değerlendiriciyi etkileyecek şekilde akıcı ve kurumsal bir dille anlat.',
          },
        },
        {
          id: 'bg_activities_in_field',
          fieldCode: 'ii. What are your organisation\'s activities in the field of this application?',
          label: 'Activities in the field of this application',
          description: 'Projenin konusu olan meslek alanındaki (örn: Bilişim, Makine, Elektrik) mevcut atölye ve eğitim faaliyetleri.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2500 },
          guidance: {
            school: 'Başvuru yapılan spesifik meslek alanındaki atölye donanımınız, haftalık staj saatleri ve mevcut müfredat uygulamaları vurgulanmalıdır.',
            host: 'Host kurumun staj vereceği sektörle okuldaki bu alanın ne kadar örtüştüğü açıkça gösterilmelidir.',
            aiPromptTemplate: 'Başvuru yapılan alan: {vetField}. Okulda bu alandaki mevcut atölye çalışmaları ve öğrencilerin aldığı dersler: {skills}. Kurumun bu alandaki faaliyetlerini ve sektörel yetkinliğini açıklayan detaylı metin oluştur.',
          },
        },
        {
          id: 'bg_learners_profile',
          fieldCode: 'iii. Please describe the learners concerned by your organisation\'s daily work. What are their profiles and age groups? In particular, please mention if you are regularly working with participants with fewer opportunities, and how.',
          label: 'Learners profile, age groups & Inclusion (Fewer opportunities)',
          description: 'Öğrenci profili, yaş grubu ve İMKANLARI KISITLI (Inclusion) katılımcılarla çalışma durumu (30 PUAN İÇİN EN KRİTİK ALAN).',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 200, maxChars: 3000 },
          guidance: {
            school: '⚠️ ÇOK KRİTİK DEĞERLENDİRME KRİTERİ: Değerlendiriciler bu soruda "Inclusion" vurgusuna çok yüksek puan verir. Öğrencilerin yaş grubu (15-18), sosyo-ekonomik arka planı, kırsal/dezavantajlı bölgeden gelip gelmedikleri, parçalanmış aile çocukları veya maddi imkansızlıklar detaylandırılmalıdır.',
            host: 'Host kurumun dezavantajlı öğrencilere sağlayacağı sıcak karşılama, güvenli konaklama ve mentörlük desteğiyle bu profil tamamlanmalıdır.',
            aiPromptTemplate: 'Öğrenci yaş grubu: {ageGroup}. Dezavantaj / Kapsayıcılık faktörleri: {fewerOpportunities}. Okulun bulunduğu bölgenin sosyo-ekonomik yapısı: {city}. Erasmus+ kapsayıcılık (Inclusion) önceliğine tam yanıt verecek, öğrenci profilini ve dezavantajlarını duyarlı ve somut biçimde ortaya koyan bir metin yaz.',
          },
        },
        {
          id: 'bg_years_of_experience',
          fieldCode: 'iv. How many years of experience does your organisation have working in the field of this application?',
          label: 'Years of experience in the field',
          description: 'Kurumun bu mesleki alandaki deneyim süresi (yıl).',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: { school: 'Okulun veya ilgili bölümün açılış yılından bu yana geçen süre.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'bg_num_learners',
          fieldCode: 'Number of learners',
          label: 'Number of learners in this field',
          description: 'Bu alanda eğitim alan toplam aktif öğrenci sayısı.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: { school: 'Okulunuzda bu bölümdeki toplam kayıtlı öğrenci sayısı.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'bg_num_teaching_staff',
          fieldCode: 'Number of teaching staff',
          label: 'Number of teaching staff',
          description: 'Bu alanda ders veren meslek öğretmenleri sayısı.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: { school: 'Bölümdeki meslek öğretmeni sayısı.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'bg_num_non_teaching_staff',
          fieldCode: 'Number of non-teaching staff',
          label: 'Number of non-teaching staff',
          description: 'İdari ve destek personeli sayısı.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: { school: 'Okul idaresi ve teknisyen sayısı.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'bg_past_participation_table',
          fieldCode: 'Past participation',
          label: 'Past participation table (Applicant vs Partner)',
          description: 'Kurumun geçmiş Erasmus+ başvuru ve kabul edilmiş proje sayıları.',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Avrupa Komisyonu veri tabanından OID bazlı otomatik listelenir. Eğer ilk başvurunuz ise "Newcomer" (Yeni Katılımcı) statüsü kazanırsınız ve değerlendirmede öncelik puanı alırsınız!',
            host: 'İşlem gerekmez.',
          },
        },
      ],
    },
    {
      id: 'project-objectives',
      pageNumber: 8,
      title: 'Project objectives',
      description: 'Kurumsal ihtiyaç ve güçlükler analizi, SMART proje hedefleri, başarı ölçütleri ve tematik öncelikler (40 Puanlık Proje Tasarım Kalitesi Değerlendirmesinin Çekirdeği).',
      fields: [
        {
          id: 'obj_needs_and_challenges',
          fieldCode: 'Needs and challenges',
          label: 'What are the most important needs and challenges your organisation is currently facing? How can an Erasmus+ mobility project help improve your organisation for the benefit of all of its learners? Please illustrate your answers with concrete examples.',
          description: 'Kurumun karşılaştığı en önemli ihtiyaç ve güçlükler nelerdir? Erasmus+ hareketliliği tüm öğrencilerin yararına olacak şekilde okulu nasıl geliştirecektir? Somut örneklerle açıklama.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 250, maxChars: 3500 },
          guidance: {
            school: 'Atölyelerinizdeki teknolojik eksiklikler, öğrencilerin mezuniyet sonrası iş bulma güçlüğü ve yabancı dil eksikliği gibi somut ve yerel verilerle desteklenmiş gerçek ihtiyaçları yazın. Genel laflardan kaçının!',
            host: 'Host kurumun sunduğu staj olanaklarının ve modern iş ortamının okulun bu ihtiyaçlarını nasıl birebir çözeceği eşleştirilmelidir.',
            aiPromptTemplate: 'Meslek alanı: {vetField}. Okulun temel ihtiyacı: {institutionNeed}. Öğrenci yeterlilik açığı: {primaryGap}. Okulun karşılaştığı teknolojik ve pedagojik güçlükleri anlatan, Erasmus hareketliliğinin bu güçlükleri nasıl çözeceğini somut örneklerle ortaya koyan ikna edici bir ihtiyaç analizi metni oluştur.',
          },
        },
        {
          id: 'obj_title_1',
          fieldCode: 'Objective 1 - Title',
          label: 'Objective 1: What do you want to achieve?',
          description: 'Hedef 1 Başlığı (Örn: Öğrencilerin 5 Eksenli CNC İşleme Teknolojilerinde Uygulamalı Beceri Kazanması).',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 15, maxChars: 250 },
          guidance: {
            school: 'Hedef SMART (Spesifik, Ölçülebilir, Ulaşılabilir, İlgili, Zamanlı) olmalıdır.',
            host: 'Hedef başlığı doğrudan staj yapılacak alanla eşleşmelidir.',
            aiPromptTemplate: 'Öğrenci teknik kazanımı: {technicalOutcome}. Alan: {vetField}. Değerlendirici standartlarına tam uyumlu 1 adet SMART Proje Hedefi Başlığı yaz.',
          },
        },
        {
          id: 'obj_explanation_1',
          fieldCode: 'Objective 1 - Explanation',
          label: 'Objective 1: Which needs and challenges described in the previous question are addressed by this objective, and how?',
          description: 'Bu hedef önceki soruda belirtilen hangi kurumsal ihtiyaç ve güçlüklere, nasıl yanıt veriyor?',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2500 },
          guidance: {
            school: 'İhtiyaç analiziyle hedef arasındaki sebep-sonuç bağını kurun. "Şu eksiğimiz vardı, bu hareketlilik sayesinde bu hedefi koyduk ve şu şekilde kapatacağız" kurgusu esastır.',
            host: 'Host işletmede uygulanacak müfredat bu hedefin "nasıl" çözüleceğinin en somut kanıtıdır.',
            aiPromptTemplate: 'Kurumsal ihtiyaç: {institutionNeed}. Hedef başlığı: {objTitle1}. Host staj içeriği: {technicalOutcome}. Bu hedefin ihtiyaçları nasıl doğrudan karşıladığını açıklayan ayrıntılı değerlendirme metni yaz.',
          },
        },
        {
          id: 'obj_measuring_success_1',
          fieldCode: 'Objective 1 - Measuring success',
          label: 'Objective 1: How are you going to evaluate if the objective has been reached?',
          description: 'Hedefe ulaşıldığını nasıl ölçeceksiniz? (Başarı göstergeleri, ölçme-değerlendirme araçları, Europass, anketler).',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 100, maxChars: 2000 },
          guidance: {
            school: 'Sadece "sertifika vereceğiz" demek yetersizdir! Ön-test / son-test (pre-test/post-test), işletme mentörü rubriği, Europass Hareketlilik Belgesi, beceri takip çizelgeleri ve mezuniyet sonrası istihdam takibi gibi çok katmanlı ölçüm yöntemleri belirtilmelidir.',
            host: 'Host kurum mentörünün yapacağı haftalık değerlendirme formu ve staj sonu beceri değerlendirme sınavı burada somut kanıt olarak sunulur.',
            aiPromptTemplate: 'Hedef: {objTitle1}. Bu hedefin gerçekleştiğini kanıtlayacak nicel (sayısal yüzde, puan artışı) ve nitel (mentör raporu, Europass, performans rubriği) ölçme ve değerlendirme metodolojisi oluştur.',
          },
        },
        {
          id: 'obj_project_topics',
          fieldCode: 'What topics are you going to work on in your project?',
          label: 'Project Topics (Thematic Priorities)',
          description: 'Projenin hizmet ettiği resmi Erasmus+ tematik öncelikleri (En fazla 3 konu seçilebilir: Yeşil beceriler, Dijitalleşme, İstihdam edilebilirlik, Kapsayıcılık vb.).',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: {
            school: 'Projenizin mesleki odağına göre en uygun 2 veya 3 önceliği seçin (Örn: "Employability", "Green skills", "Digital competencies").',
            host: 'Host kurumun profili seçilen bu önceliklerle (örn. çevre dostu üretim, dijital otomasyon) uyumlu olmalıdır.',
          },
        },
      ],
    },
    {
      id: 'activities',
      pageNumber: 9,
      title: 'Activities',
      description: 'Faaliyet türleri, öğrenci ve refakatçi kişi sayıları, süreler ve talep edilen hibe toplamı tablosu.',
      fields: [
        {
          id: 'act_table_type',
          fieldCode: 'Activity type',
          label: 'Activity type',
          description: 'Resmi faaliyet türü: Kısa dönem VET öğrenici hareketliliği (10-89 gün), ErasmusPro uzun dönem (90-365 gün) veya Personel İşbaşı İzleme (Job Shadowing).',
          fillStrategy: 'DIRECT_AUTOFILL',
          sourceKey: 'mobility.activityType',
          rules: { isMandatory: true },
          guidance: {
            school: 'Öğrenciler için "Short-term learning mobility of VET learners" en yaygın kullanılanıdır. Personel için "Job shadowing" seçilebilir.',
            host: 'Host kurumun stajyer kapasitesi (maxLearnersPerTerm) ile tam uyumlu olmalıdır.',
          },
        },
        {
          id: 'act_table_num_participants',
          fieldCode: 'Number of participants',
          label: 'Number of participants',
          description: 'Faaliyete katılacak toplam öğrenci sayısı.',
          fillStrategy: 'DIRECT_AUTOFILL',
          sourceKey: 'mobility.participantCount',
          rules: { isMandatory: true },
          guidance: {
            school: 'KA122 için bir projede maksimum katılımcı sınırı genellikle 30 katılımcıdır (refakatçiler ve hazırlık ziyaretleri hariç). Bu sınır aşılmamalıdır.',
            host: 'Host firmanın eşzamanlı ağırlayabileceği öğrenci sayısı ile doğrulanmalıdır.',
          },
        },
        {
          id: 'act_table_duration_participants',
          fieldCode: 'Total duration for participants (in days)',
          label: 'Total duration for participants (in days)',
          description: 'Tüm öğrencilerin toplam staj/öğrenme gün sayısı.',
          fillStrategy: 'SYSTEM_GENERATED',
          sourceKey: 'mobility.totalActivityDays',
          rules: { isMandatory: true },
          guidance: {
            school: 'Öğrenci sayısı x Staj gün sayısı formülüyle otomatik hesaplanır.',
            host: 'İşletme staj takvimi ile netleştirilir.',
          },
        },
        {
          id: 'act_table_num_accompanying',
          fieldCode: 'Number of accompanying persons',
          label: 'Number of accompanying persons',
          description: 'Öğrencilere refakat edecek meslek öğretmeni sayısı.',
          fillStrategy: 'DIRECT_AUTOFILL',
          sourceKey: 'mobility.accompanyingPersonsCount',
          rules: { isMandatory: true },
          guidance: {
            school: '18 yaş altı meslek lisesi öğrencileri için her 5-7 öğrenciye 1 refakatçi öğretmen atanması tavsiye edilir.',
            host: 'Refakatçi öğretmen için konaklama ve mentör koordinasyon alanı tahsis edilmelidir.',
          },
        },
        {
          id: 'act_table_duration_accompanying',
          fieldCode: 'Total duration for accompanying persons (in days)',
          label: 'Total duration for accompanying persons (in days)',
          description: 'Refakatçilerin toplam gün sayısı.',
          fillStrategy: 'DIRECT_AUTOFILL',
          rules: { isMandatory: true },
          guidance: {
            school: 'Refakatçi sayısı x refakat günü formülüyle hesaplanır.',
            host: 'İşlem gerekmez.',
          },
        },
        {
          id: 'act_table_total_grant',
          fieldCode: 'Total Grant (EUR)',
          label: 'Total Grant (EUR)',
          description: 'Bu faaliyet için talep edilen toplam hibe tutarı (Bireysel destek + Seyahat + Kurumsal destek toplamı).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Erasmus+ birim maliyet kurallarına göre sistem tarafından kuruşu kuruşuna otomatik hesaplanır.',
            host: 'Projenin toplam bütçe büyüklüğüdür.',
          },
        },
      ],
    },
    {
      id: 'budget',
      pageNumber: 10,
      title: 'Budget summary & Details',
      description: 'Resmi birim maliyet kalemlerine göre hesaplanan bütçe özeti ve detay tabloları.',
      fields: [
        {
          id: 'bgt_organisational_support',
          fieldCode: 'Organisational support (EUR)',
          label: 'Organisational support (EUR)',
          description: 'Kurumsal destek hibesi (Katılımcı başına 100 EUR).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Katılımcı sayısı x 100 EUR olarak otomatik hesaplanır. Okulun hazırlık, idari işler ve sigorta giderleri için kullanılır.',
            host: 'İşlem gerekmez.',
          },
        },
        {
          id: 'bgt_individual_support',
          fieldCode: 'Individual support (EUR)',
          label: 'Individual support (EUR)',
          description: 'Katılımcı ve refakatçilerin günlük cep harçlığı, yeme-içme ve konaklama hibesi (Ülke grubu ve gün sayısına göre).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Gidilecek ülkenin pahalılık grubuna (Group 1: Almanya, İrlanda; Group 2: İspanya, İtalya; Group 3: Polonya vb.) göre günlük taban oran x gün sayısı formülüyle otomatik hesaplanır.',
            host: 'Host kurumun sağladığı konaklama ve yemek maliyetleri bu bütçeden karşılanır.',
          },
        },
        {
          id: 'bgt_travel',
          fieldCode: 'Travel (EUR)',
          label: 'Travel (EUR)',
          description: 'Mesafe bandına göre seyahat hibesi (Standart uçak veya Yeşil seyahat).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Avrupa Komisyonu Mesafe Hesaplayıcısı (Distance Calculator) km aralığına göre (Örn: 2000-2999 km için 360 EUR, Yeşil seyahat için 417 EUR) otomatik hesaplanır.',
            host: 'Host şehrine ulaşım mesafesi baz alınır.',
          },
        },
        {
          id: 'bgt_course_fees',
          fieldCode: 'Course fees (EUR)',
          label: 'Course fees (EUR)',
          description: 'Kurs ücreti hibesi (Öğrenci stajlarında "Not applicable"; personel kurslarında günlük 80 EUR, maks 800 EUR).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'VET öğrenci stajlarında bu alan sistem tarafından otomatik "Not applicable" yapılır.',
            host: 'İşlem gerekmez.',
          },
        },
        {
          id: 'bgt_linguistic_support',
          fieldCode: 'Linguistic support (EUR)',
          label: 'Linguistic support (EUR)',
          description: 'Dil desteği (Online Dil Desteği - OLS ücretsizdir; OLS dışı diller veya uzun dönem staj için kişi başı 150 EUR hibe).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Komisyonun OLS platformu üzerinden ücretsiz dil eğitimi sağlanır.',
            host: 'Host ülkede konuşulan dil veya işletme çalışma dili (İngilizce, Almanca vb.) ile uyumlu olmalıdır.',
          },
        },
        {
          id: 'bgt_preparatory_visits',
          fieldCode: 'Preparatory visits (EUR)',
          label: 'Preparatory visits (EUR)',
          description: 'Hazırlık ziyareti hibesi (Kişi başı sabit 680 EUR birim hibe).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Yeni bir host ile ilk kez çalışılıyorsa veya ErasmusPro uzun dönem stajı varsa kişi başı 680 EUR hibe talep edilebilir (Ziyaret başına maks 3 kişi).',
            host: 'Host kurum okulu yerinde ağırlamak üzere hazırlık yapar.',
          },
        },
        {
          id: 'bgt_inclusion_support_org',
          fieldCode: 'Inclusion support for organisations (EUR)',
          label: 'Inclusion support for organisations (EUR)',
          description: 'İmkanları kısıtlı katılımcı başına kuruma verilen ek kurumsal destek hibesi (Kişi başı sabit 125 EUR).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Dezavantajlı katılımcı sayısı x 125 EUR olarak bütçeye otomatik eklenir.',
            host: 'İşlem gerekmez.',
          },
        },
        {
          id: 'bgt_total_grant',
          fieldCode: 'Total (EUR)',
          label: 'Total Project Grant (EUR)',
          description: 'Tüm bütçe kalemlerinin genel toplamı.',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Sistem tüm kalemleri otomatik toplayarak resmi başvuru tutarını üretir.',
            host: 'Projenin nihai onaylanacak hibe tutarıdır.',
          },
        },
      ],
      subsections: [
        {
          id: 'organisational-support',
          pageNumber: 11,
          title: 'Organisational support',
          description: 'Hareketlilik akışı (Mobility Flow) bazında katılımcı ve refakatçilerin kurumsal destek hibesi dökümü.',
          fields: [
            {
              id: 'os_flow_id',
              fieldCode: 'Mobility flow ID',
              label: 'Mobility flow ID',
              fillStrategy: 'SYSTEM_GENERATED',
              rules: { isMandatory: true },
              guidance: { school: 'Sistem tarafından sıralı akış kodu olarak atanır (01, 02 vb.).', host: 'İşlem gerekmez.' },
            },
            {
              id: 'os_activity_type',
              fieldCode: 'Activity type',
              label: 'Activity type',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: { school: 'Faaliyet türü (Örn: Short-term mobility of VET learners).', host: 'İşlem gerekmez.' },
            },
            {
              id: 'os_destination_country',
              fieldCode: 'Destination country',
              label: 'Destination country',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: { school: 'Gidilecek ülke (Örn: Almanya, İtalya, İspanya).', host: 'Host kurumun ülkesi.' },
            },
            {
              id: 'os_num_participants',
              fieldCode: 'Number of participants',
              label: 'Number of participants',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: { school: 'Akıştaki öğrenci sayısı.', host: 'Stajyer sayısı.' },
            },
            {
              id: 'os_num_accompanying',
              fieldCode: 'Number of accompanying persons',
              label: 'Number of accompanying persons',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: { school: 'Akıştaki refakatçi öğretmen sayısı.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'os_unit_cost',
              fieldCode: 'Organisational support unit cost (EUR)',
              label: 'Unit cost (EUR)',
              description: 'Katılımcı başına sabit birim maliyet (100 EUR).',
              fillStrategy: 'SYSTEM_GENERATED',
              rules: { isMandatory: true },
              guidance: { school: 'Sabit 100 EUR.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'os_total_grant',
              fieldCode: 'Organisational support grant (EUR)',
              label: 'Organisational support grant (EUR)',
              description: 'Katılımcı sayısı x Birim maliyet toplamı.',
              fillStrategy: 'SYSTEM_GENERATED',
              rules: { isMandatory: true },
              guidance: {
                school: '⚠️ KRİTİK İŞBİRLİĞİ KURALI: Resmi Erasmus+ kuralına göre Kurumsal Destek (OS) hibesi hem gönderen okulun hem ev sahibi (host) kurumun hazırlık, izleme ve mentörlük masraflarını kapsar ve iki kurum arasında görev dağılımına göre paylaşılmalıdır.',
                host: 'Öğrencilere mentörlük, oryantasyon ve yerel destek sağlayan host kurum, okul ile yapacağı ortaklık sözleşmesinde bu kurumsal destek hibesinden pay alabilir.',
              },
            },
          ],
        },
        {
          id: 'inclusion-support',
          pageNumber: 12,
          title: 'Inclusion support',
          description: 'İmkanları kısıtlı katılımcılar için kuruma verilen sabit hibe (125 EUR) ve %100 gerçek maliyet esaslı katılımcı desteği.',
          fields: [
            {
              id: 'inc_flow_id',
              fieldCode: 'Mobility Flow ID',
              label: 'Mobility Flow ID',
              fillStrategy: 'SYSTEM_GENERATED',
              rules: { isMandatory: true },
              guidance: { school: 'Akış numarası (Örn: 01).', host: 'İşlem gerekmez.' },
            },
            {
              id: 'inc_activity_type',
              fieldCode: 'Activity type',
              label: 'Activity type',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: { school: 'Faaliyet türü.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'inc_destination_country',
              fieldCode: 'Destination country',
              label: 'Destination country',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: { school: 'Hedef ülke.', host: 'Host kurum ülkesi.' },
            },
            {
              id: 'inc_total_participants',
              fieldCode: 'Number of participants in the mobility flow',
              label: 'Total participants in flow',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: { school: 'Akıştaki toplam katılımcı sayısı.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'inc_fewer_opp_count',
              fieldCode: 'Number of participants with fewer opportunities',
              label: 'Participants with fewer opportunities',
              description: 'Sosyal, ekonomik, sağlık veya engellilik bariyeri olan katılımcı sayısı.',
              fillStrategy: 'DIRECT_AUTOFILL',
              sourceKey: 'mobility.fewerOpportunitiesCount',
              rules: { isMandatory: true },
              guidance: { school: 'Dezavantajlı öğrenci sayısı girilir.', host: 'Erişilebilirlik planı için gereklidir.' },
            },
            {
              id: 'inc_org_grant',
              fieldCode: 'Inclusion support for organisations (EUR)',
              label: 'Inclusion support for organisations (EUR)',
              description: 'Kuruma dezavantajlı katılımcı başına verilen ek idari hibe (Kişi başı 125 EUR).',
              fillStrategy: 'SYSTEM_GENERATED',
              rules: { isMandatory: true },
              guidance: { school: 'Sistem otomatik hesaplar (Dezavantajlı kişi x 125 EUR).', host: 'İşlem gerekmez.' },
            },
            {
              id: 'inc_part_grant',
              fieldCode: 'Inclusion support for participants (EUR)',
              label: 'Inclusion support for participants (EUR)',
              description: 'Özel refakatçi, medikal cihaz, tercüman veya özel konaklama gibi %100 gerçek masraf hibesi.',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: {
                school: 'Öğrencinin standart hibe ile karşılanamayacak özel ihtiyaçları varsa buraya gerçek maliyeti yazılır.',
                host: 'Host lokasyonundaki özel erişim veya medikal destek tekliflerini sağlar.',
              },
            },
          ],
        },
        {
          id: 'exceptional-costs',
          pageNumber: 13,
          title: 'Exceptional costs',
          description: 'Giriş gereksinimleri (Vize, oturum izni, aşı, sağlık raporu) ve Ulusal Ajans finansal teminat masrafları.',
          fields: [
            {
              id: 'exc_cost_type',
              fieldCode: 'Cost type',
              label: 'Cost type',
              description: 'Masraf kalemi (Vize masrafları, oturum izni, sağlık raporları veya Finansal Teminat).',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true, allowedValues: ['Visas and visa-related costs', 'Financial guarantee'] },
              guidance: {
                school: 'Schengen vizesi harçları, aracı kurum (VFS/iDATA vb.) ücretleri ve vize için zorunlu sağlık raporu maliyetleri buraya yazılabilir.',
                host: 'Host kurum vize için resmi kabul mektubu (Letter of Acceptance) ve staj davetiyesini temin eder.',
              },
            },
            {
              id: 'exc_desc_justification',
              fieldCode: 'Description and justification of expenses (EUR)',
              label: 'Description and justification of expenses',
              description: 'Harcamanın neden zorunlu olduğunu açıklayan resmi gerekçe metni.',
              fillStrategy: 'AI_ASSISTED',
              rules: { isMandatory: true, minChars: 100, maxChars: 1500 },
              guidance: {
                school: 'Vize harçları ve zorunlu konsolosluk randevu masrafları şeffaf birim fiyatlarıyla yazılmalıdır.',
                host: 'İşlem gerekmez.',
                aiPromptTemplate: 'Gidilecek ülke: {destinationCountry}. Katılımcı sayısı: {participantCount}. Talep edilen vize ve resmi giriş masrafları: {estimatedCost} EUR. Standart hibenin vize süreçlerini neden karşılamadığını ve bu desteğin hareketliliğin gerçekleşmesi için neden elzem olduğunu açıklayan resmi gerekçe yaz.',
              },
            },
            {
              id: 'exc_eligible_costs',
              fieldCode: 'Eligible costs (EUR)',
              label: 'Eligible costs (EUR)',
              description: 'Gerçekleşmesi öngörülen toplam masraf tutarı.',
              fillStrategy: 'DIRECT_AUTOFILL',
              rules: { isMandatory: true },
              guidance: { school: 'Toplam vize/giriş faturası tahmini.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'exc_support_rate',
              fieldCode: 'Support Rate (%)',
              label: 'Support Rate (%)',
              description: 'Hibe oranı (Vize ve seyahat belgeleri için %100).',
              fillStrategy: 'SYSTEM_GENERATED',
              rules: { isMandatory: true },
              guidance: { school: 'Vize ve resmi giriş masrafları %100 karşılanır.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'exc_eligible_amount',
              fieldCode: 'Eligible amount',
              label: 'Eligible amount (EUR)',
              description: 'Talep edilecek nihai hibe miktarı.',
              fillStrategy: 'SYSTEM_GENERATED',
              rules: { isMandatory: true },
              guidance: { school: 'Sistem otomatik hesaplar.', host: 'İşlem gerekmez.' },
            },
            {
              id: 'exc_fin_guarantee_chk',
              fieldCode: 'Financial guarantee checkbox',
              label: 'The National Agency has requested a financial guarantee.',
              description: 'Ulusal Ajansın finansal teminat mektubu talep etmesi halinde işaretlenecek kutucuk.',
              fillStrategy: 'DECLARATION',
              rules: { isMandatory: false },
              guidance: {
                school: 'Milli Eğitim Bakanlığına bağlı devlet okullarından finansal teminat istenmez; kutucuk boş bırakılır. Sadece özel kurumlar için gerekebilir.',
                host: 'İşlem gerekmez.',
              },
            },
          ],
        },
      ],
    },
    {
      id: 'quality-standards',
      pageNumber: 14,
      title: 'Erasmus Quality Standards',
      description: 'Erasmus Kalite Standartlarına uyum taahhüdü: Temel İlkeler (Kapsayıcılık, Yeşil, Dijital), İyi Yönetim (Çekirdek görevlerin devredilemezliği, Katılımcı ücretleri yasağı) ve Sonuçların Entegrasyonu (40 Puanlık Tasarım Kalitesi Değerlendirmesi).',
      fields: [
        {
          id: 'qs_inclusion_diversity',
          fieldCode: 'I. Basic principles: Inclusion and diversity',
          label: 'Inclusion and diversity adherence',
          description: 'İmkanları kısıtlı katılımcıların projeye aktif dahil edilmesi, eşit şartlar ve kapsayıcılık ilkelerine uyum.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Seçim sürecinde sosyo-ekonomik dezavantajlı, kırsal veya engelli öğrencilere pozitif ayrımcılık yapılmalı ve fonlar sonuna kadar kullanılmalıdır.',
            host: 'Ev sahibi kurum tüm katılımcılara eşit, adil, ayrımcılık karşıtı bir staj ortamı ve erişilebilirlik sağlamakla yükümlüdür.',
          },
        },
        {
          id: 'qs_environmental_sustainability',
          fieldCode: 'I. Basic principles: Environmental sustainability and responsibility',
          label: 'Environmental sustainability and responsibility (Green travel)',
          description: 'Çevre dostu sürdürülebilir davranışların teşvik edilmesi ve Yeşil Seyahat (Green Travel) fonlarının azami kullanımı.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Katılımcıların tren/otobüsle seyahat etmesi teşvik edilmeli; hareketlilik süresince çevre bilinci ve atık azaltma kuralları uygulanmalıdır.',
            host: 'Host kurum staj süresince enerji tasarrufu, geri dönüşüm ve yeşil üretim tekniklerini stajyerlere aktarır.',
          },
        },
        {
          id: 'qs_digital_education',
          fieldCode: 'I. Basic principles: Digital education and blended mobility',
          label: 'Digital education and blended mobility',
          description: 'Fiziksel hareketliliği tamamlamak üzere dijital araçların, çevrimiçi işbirliğinin ve harmanlanmış öğrenmenin (blended mobility) kullanımı.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Hareketlilik öncesi online tanışma/oryantasyon oturumları, dijital portfolyo ve eTwinning/ESEP araçları kullanılmalıdır.',
            host: 'Staj öncesinde öğrencilere online teknik dokümanlar ve uzaktan hazırlık görevleri vererek karma öğrenmeye katkı sunar.',
          },
        },
        {
          id: 'qs_active_participation',
          fieldCode: 'I. Basic principles: Active participation in the network',
          label: 'Active participation in the network of Erasmus organisations',
          description: 'Avrupa Eğitim Alanı gelişimini desteklemek, iyi uygulamaları paylaşmak ve Erasmus ağına aktif katılım.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Proje çıktıları diğer meslek liseleriyle paylaşılmalı ve mezunlar ağı (alumni) kurulmalıdır.',
            host: 'Uluslararası stajyer ağına dahil olarak diğer ülkelerle iyi uygulamaları paylaşır.',
          },
        },
        {
          id: 'qs_core_tasks_ownership',
          fieldCode: 'II. Good management: Core tasks - keeping ownership of the activities',
          label: 'Core tasks - keeping ownership of the activities (Cannot outsource)',
          description: '⚠️ EN KRİTİK İDARİ KURAL: Yararlanıcı kurum ana görevlerin mülkiyetini elinde tutmalı ve bu görevleri başka kurumlara DEVRETMEMELİDİR (taşerona verilemez).',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: '⚠️ ÇOK KATI KURAL: Bütçe yönetimi, Ulusal Ajansla iletişim, faaliyetlerin raporlanması, host kurum seçimi ve öğrenme çıktılarının belirlenmesi/değerlendirilmesi gibi çekirdek görevler ASLA harici bir aracı/danışman firmaya devredilemez!',
            host: 'Host kurum ev sahibi olarak staj ve eğitim içeriklerini sağlar; ancak projenin yasal ve mali liderliği daima okulun elindedir.',
          },
        },
        {
          id: 'qs_supporting_org_rules',
          fieldCode: 'II. Good management: Supporting organisations, transparency and responsibility',
          label: 'Supporting organisations transparency and risk sharing',
          description: 'Destekleyen kuruluş kullanılıyorsa şeffaflık, yazılı sözleşme, risk paylaşımı ve resmi raporlama araçlarına kayıt zorunluluğu.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Pratik işler için destek alınıyorsa yazılı sözleşme yapılmalı ve Ulusal Ajans araçlarına kaydedilmelidir. Ancak öğrenme ve mentörlük veren host kurumlar bu kapsamda değil doğrudan ortaktır.',
            host: 'İşlem gerekmez.',
          },
        },
        {
          id: 'qs_participant_contributions',
          fieldCode: 'II. Good management: Contributions paid by participants',
          label: 'No unfair participant contributions rule',
          description: 'Katılımcılardan haksız ücret/katkı payı alınması yasağı. Eş finansman gerekse bile kar amacı gütmeme ve dezavantajlılara bariyer oluşturmama kuralı.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: '⚠️ KESİN YASAK: Öğrencilerden haksız ek ücretler toplanamaz! Aracı kuruluşların veya okulların öğrencilerden gayriresmi para toplaması sözleşme feshine ve hibe iadesine yol açar.',
            host: 'Host kurum stajyerlerden herhangi bir ad altında ek ücret talep edemez; tüm masraflar resmi hibeden karşılanır.',
          },
        },
        {
          id: 'qs_integrating_results',
          fieldCode: 'II. Good management: Integrating results of mobility activities in the organisation',
          label: 'Integrating results in the organisation',
          description: 'Hareketlilikte kazanılan bilgi ve becerilerin kurumun günlük işleyişine, atölyelerine ve müfredatına entegre edilmesi.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Dönen öğrencilerin atölyelerde akran eğitimi vermesi, öğretmenlerin öğrendiği teknikleri zümre toplantılarında müfredata aktarması zorunludur.',
            host: 'Öğrencinin stajda ne öğrendiğini belgeleyen ayrıntılı kazanım raporu sunarak entegrasyona destek olur.',
          },
        },
        {
          id: 'qs_gathering_feedback',
          fieldCode: 'II. Good management: Gathering and using participants\' feedback',
          label: 'Gathering and using participants feedback (EU Survey)',
          description: 'Katılımcıların resmi AB anketini doldurmasının sağlanması ve geri bildirimlerin gelecek faaliyetlerin iyileştirilmesinde kullanılması.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Dönen her katılımcının sistemdeki resmi anketini eksiksiz tamamlaması takip edilmelidir.',
            host: 'Staj sonu anket ve değerlendirmelerini düzenli yaparak kalite döngüsünü tamamlar.',
          },
        },
        {
          id: 'qs_practical_arrangements',
          fieldCode: 'III. Participant support: Practical arrangements',
          label: 'Practical and logistic arrangements',
          description: 'Seyahat, konaklama, vize, sigorta ve lojistik düzenlemelerin kalitesinden birincil sorumluluk.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Konaklama ve seyahat lojistiğinde son denetim ve onay sorumluluğu okula aittir.',
            host: 'Güvenli, temiz, staj yerine kolay ulaşılabilir konaklama ve transfer altyapısını organize eder.',
          },
        },
        {
          id: 'qs_health_safety_insurance',
          fieldCode: 'III. Participant support: Health, safety and respect of applicable regulation',
          label: 'Health, safety, parental consent and insurance coverage',
          description: 'İş sağlığı ve güvenliği (OHS), veli izinleri, 18 yaş altı koruma standartları ve tam kapsamlı seyahat/sağlık/mesuliyet sigortası.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Tüm öğrenciler için veli izin belgeleri ve 3 ana sigorta (Sağlık, Kaza, Mesleki Mesuliyet) eksiksiz yaptırılmalıdır.',
            host: 'İşletmelerde İSG (İş Sağlığı ve Güvenliği) koruyucu donanımlarını (yelek, gözlük, çelik burunlu ayakkabı) temin eder.',
          },
        },
        {
          id: 'qs_selection_procedure',
          fieldCode: 'III. Participant support: Selection of participants',
          label: 'Transparent, fair and inclusive selection procedure',
          description: 'Katılımcıların şeffaf, adil, liyakate dayalı ve kapsayıcı (dezavantajlılara fırsat tanıyan) kriterlerle seçilmesi.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Seçim kriterleri (yabancı dil, mesleki başarı, mülakat ve dezavantaj puanı) önceden ilan edilmeli, tutanak altına alınmalı ve asil/yedek liste yayınlanmalıdır.',
            host: 'İşlem gerekmez.',
          },
        },
        {
          id: 'qs_preparation',
          fieldCode: 'III. Participant support: Preparation',
          label: 'Pedagogical, cultural and practical preparation',
          description: 'Katılımcıların gitmeden önce pratik, mesleki ve kültürel olarak host kurum işbirliğiyle hazırlanması.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Gidiş öncesi en az 20 saatlik pedagojik, mesleki ve kültürel oryantasyon eğitimi düzenlenmelidir.',
            host: 'Gidilecek şehir, şirket kuralları ve yerel kültür hakkında tanıtım materyali sağlar.',
          },
        },
        {
          id: 'qs_monitoring_mentoring',
          fieldCode: 'III. Participant support: Monitoring and mentoring',
          label: 'Designated mentor at hosting organisation and continuous monitoring',
          description: 'Ev sahibi kurumda her katılımcıya özel atanmış bir staj mentörü bulunması ve öğrenme sürecinin izlenmesi.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Refakatçi öğretmen her gün işletmeleri ziyaret ederek mentör ile koordinasyon sağlar.',
            host: 'Host kurum stajyerin başında duracak, mesleki rehberlik edecek ve haftalık gelişimini takip edecek nitelikli bir mentör görevlendirir.',
          },
        },
        {
          id: 'qs_definition_learning_outcomes',
          fieldCode: 'III. Participant support: Definition of learning outcomes',
          label: 'Learning Agreement with clear learning outcomes',
          description: 'Staj öncesinde gönderen okul, ev sahibi kurum ve öğrenci arasında imzalanan Öğrenme Anlaşması (Learning Agreement).',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Mobility Nexus Learning Agreement motoru üzerinden öğrencinin kazanacağı teknik ve transversal beceriler gitmeden önce resmi olarak tanımlanır.',
            host: 'Host kurum bu öğrenme çıktılarını staj müfredatına birebir uyarlar ve resmi olarak onaylar.',
          },
        },
        {
          id: 'qs_recognition_learning_outcomes',
          fieldCode: 'III. Participant support: Recognition of learning outcomes',
          label: 'Formal recognition and Europass Mobility Certificate',
          description: 'Kazanılan becerilerin okulda resmi olarak tanınması ve Europass Hareketlilik Belgesi düzenlenmesi.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Dönen her öğrenciye resmi Europass Hareketlilik Belgesi verilmeli ve staj okul staj yükümlülüğünden sayılmalıdır.',
            host: 'Europass belgesini ve staj başarı sertifikasını kaşeleyip imzalar.',
          },
        },
        {
          id: 'qs_sharing_results',
          fieldCode: 'IV. Sharing results: Sharing results and acknowledging EU funding',
          label: 'Dissemination and public acknowledgement of EU funding',
          description: 'Sonuçların okul içi, diğer kurumlar ve yerel halk ile paylaşılması, AB amblemi ve finansman ifadesinin görünürlüğü.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: 'Okul web sitesi, sosyal medya, yerel basın, sergi ve seminerlerle projenin yaygınlaştırılması ve AB bayrağı/hibe logosunun kullanılması zorunludur.',
            host: 'Kendi web sitesi ve bültenlerinde Türk okulu ile yürüttüğü başarılı staj projesini haberleştirir.',
          },
        },
        {
          id: 'qs_sub_read_understood',
          fieldCode: 'Subscribing to Erasmus Quality Standards - Read and Understood',
          label: 'I have read and understood the above quality standards',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Zorunlu onay kutusu.', host: 'Zorunlu taahhüt.' },
        },
        {
          id: 'qs_sub_eval_agreement',
          fieldCode: 'Subscribing to Erasmus Quality Standards - Evaluation Agreement',
          label: 'I understand and agree that these quality standards will be used as part of the criteria for evaluation of my project at final report stage',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Nihai raporda projenin bu kalite standartlarına göre puanlanacağını kabul teyidi.', host: 'İşlem gerekmez.' },
        },
      ],
    },
    {
      id: 'follow-up',
      pageNumber: 17,
      title: 'Follow-up & Dissemination',
      description: 'Temel ilkeler katkısı, proje ekibi ve görev dağılımı (İSİM YAZMADAN), sonuçların kuruma entegrasyonu ve yaygınlaştırma stratejisi (30 Puanlık Takip ve Yaygınlaştırma Değerlendirmesi).',
      fields: [
        {
          id: 'fu_basic_principles',
          fieldCode: 'Contribution to basic principles',
          label: 'What will your organisation do to contribute to the basic principles defined by the quality standards : inclusion and diversity, environmental sustainability and responsibility, digital education, and active participation in the network of Erasmus+ organisations?',
          description: 'Kurumunuz 4 temel AB önceliğine (Kapsayıcılık, Çevre/Yeşil, Dijital Eğitim, Erasmus Ağı) somut olarak nasıl katkı sunacak?',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 200, maxChars: 3000 },
          guidance: {
            school: 'Dört önceliğin her biri için okulunuzun yapacağı somut aksiyonları maddeler halinde yazın (Örn: dezavantajlı öğrenciler için burs fonu, trenle seyahat ve karbon ayak izi ölçümü, e-öğrenme modülleri, yerel ağ semineri).',
            host: 'Host kurumun sunduğu dijital staj yönetim araçları ve yeşil şirket pratikleri bu anlatımı güçlendirir.',
            aiPromptTemplate: 'Mesleki alan: {vetField}. Katılımcı profili: {participantProfile}. 4 temel ilke: (1) Kapsayıcılık ve çeşitlilik, (2) Çevresel sürdürülebilirlik (Yeşil seyahat), (3) Dijital eğitim/araçlar, (4) Erasmus ağına aktif katılım. Değerlendiriciden tam puan alacak şekilde her ilke için ayrıntılı ve somut taahhütler içeren profesyonel bir metin oluştur.',
          },
        },
        {
          id: 'fu_project_team_tasks',
          fieldCode: 'Project team and division of tasks',
          label: 'Please describe your project team and the division of tasks in it. Who will participate in the project team – please mention the persons\' roles, positions and expertise, not their names. How will the key project tasks be divided among the project team: selection of participants, preparation of participants, supporting participants during the activity, defining the learning programmes, recognition of learning outcomes, overall supervision and ensuring the respect of quality standards.',
          description: 'Proje ekibi ve görev dağılımı. ⚠️ DİKKAT: Şahıs isimleri ASLA yazılmamalı, yalnızca roller, unvanlar ve uzmanlıklar belirtilmelidir!',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 250, maxChars: 3500 },
          guidance: {
            school: '⚠️ ÇOK KESİN KURAL: Metinde Ahmet, Mehmet gibi KİŞİ İSİMLERİ YAZMAYIN! Unvan ve uzmanlık yazın (Örn: Proje Yasal Temsilcisi / Okul Müdürü, Proje İrtibat Kişisi / İngilizce Öğretmeni, Teknik Koordinatör / Bilişim Alan Şefi, Rehberlik ve Katılımcı Seçim Sorumlusu / Psikolojik Danışman).',
            host: 'Ev sahibi kurumun görevlendirdiği Şirket Staj Mentörü ve Yerel Lojistik Koordinatörü bu görev dağılımının karşı tarafındaki partnerler olarak tarif edilmelidir.',
            aiPromptTemplate: 'Okul türü: {schoolType}. Mesleki alan: {vetField}. Kişi isimleri kullanmaksızın, tamamen kurumsal roller (Okul Müdürü, Alan Şefi, Yabancı Dil Öğretmeni, Rehber Öğretmen vb.) üzerinden katılımcı seçimi, hazırlık, refakat, staj müfredatı tanımlama, Europass tanıma ve kalite denetimi görevlerini net bir şekilde paylaştıran profesyonel bir Proje Ekibi Görev Dağılımı metni oluştur.',
          },
        },
        {
          id: 'fu_integrating_results',
          fieldCode: 'Integrating results in regular work',
          label: 'What will you do to integrate the results of implemented mobility activities in your organisation\'s regular work?',
          description: 'Hareketlilik çıktılarının okulun rutin eğitim ve atölye süreçlerine nasıl entegre edileceği.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 150, maxChars: 2500 },
          guidance: {
            school: 'Dönen öğrencilerin atölyelerde arkadaşlarına yeni teknikleri öğretmesi (akran eğitimi), öğretmenlerin zümre toplantılarında ders planlarını Avrupa standartlarına göre güncellemesi ve okulun yıllık gelişim planına entegrasyonu yazılmalıdır.',
            host: 'Host firmanın sağladığı teknik dokümantasyon, çalışma kılavuzları ve vaka analizleri okulun atölye derslerinde kalıcı eğitim materyali olarak kullanılır.',
            aiPromptTemplate: 'Öğrenilen teknik kazanımlar: {technicalOutcome}. Alan: {vetField}. Staj sonrasında elde edilen bu modern sektörel bilgi ve becerilerin okulun müfredatına, atölye derslerine ve diğer tüm öğrencilere nasıl kalıcı şekilde entegre edileceğini açıklayan somut bir plan hazırla.',
          },
        },
        {
          id: 'fu_share_within_org',
          fieldCode: 'Sharing results: i. Within your organisation',
          label: 'Sharing results: i. To share results within your organisation',
          description: 'Sonuçların okul içinde (öğrenciler, öğretmenler, veliler) nasıl paylaşılacağı.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 100, maxChars: 1500 },
          guidance: {
            school: 'Okul konferans salonunda deneyim paylaşım günü, okul panoları, veli bilgilendirme toplantıları ve atölye içi sunumlar.',
            host: 'İşlem gerekmez.',
            aiPromptTemplate: 'Okul içi yaygınlaştırma faaliyetleri: Deneyim paylaşım semineri, okul panosu, e-bülten, atölye sunumları. Değerlendiriciye yönelik somut okul içi yaygınlaştırma paragrafı yaz.',
          },
        },
        {
          id: 'fu_share_public',
          fieldCode: 'Sharing results: ii. With other organisations and the public',
          label: 'Sharing results: ii. To share results with other organisations and the public',
          description: 'Sonuçların diğer okullar, yerel sektör, meslek odaları ve kamuoyu ile nasıl paylaşılacağı.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 100, maxChars: 1500 },
          guidance: {
            school: 'İl/İlçe Milli Eğitim Müdürlüğü toplantıları, Sanayi/Ticaret Odası ziyareti, yerel basın bültenleri, sosyal medya ve EPRP (Erasmus Proje Sonuçları Platformu) kullanımı.',
            host: 'Host kurumun yerel ağları ve web sitesinde ortak projenin duyurulması.',
            aiPromptTemplate: 'Kurum şehri: {city}, Alan: {vetField}. Diğer meslek liseleri, organize sanayi bölgesi (OSB) ve yerel basınla paylaşımı içeren zengin bir kamuya açık yaygınlaştırma planı oluştur.',
          },
        },
        {
          id: 'fu_acknowledge_funding',
          fieldCode: 'Sharing results: iii. Publicly acknowledge European Union funding',
          label: 'Sharing results: iii. To publicly acknowledge European Union funding',
          description: 'Avrupa Birliği finansmanının ve hibe logosunun halka açık görünürlüğünün nasıl sağlanacağı.',
          fillStrategy: 'AI_ASSISTED',
          rules: { isMandatory: true, minChars: 80, maxChars: 1000 },
          guidance: {
            school: '"Avrupa Birliği tarafından finanse edilmektedir" resmi ifadesi, AB bayrağı logosu, projenin web sayfasında feragatname (disclaimer) ve tüm basılı/dijital materyallerde görünürlük kurallarına uyulacağı beyan edilir.',
            host: 'Ortak sertifikalarda ve staj programı belgelerinde AB logosu kullanılır.',
            aiPromptTemplate: 'Erasmus+ görünürlük kurallarına (EU emblem, "Co-funded by the European Union" ibaresi, feragat metni) tam uyumu taahhüt eden resmi görünürlük paragrafı yaz.',
          },
        },
      ],
    },
    {
      id: 'annexes',
      pageNumber: 18,
      title: 'Annexes',
      description: 'Zorunlu Doğruluk Beyanı (Declaration on Honour - DoH) belgesinin yüklenmesi.',
      fields: [
        {
          id: 'annex_declaration_on_honour',
          fieldCode: 'Declaration on Honour',
          label: 'Declaration on Honour (DoH)',
          description: 'Okul Müdürü (Yasal Temsilci) tarafından mavi kalemle imzalanıp mühürlenmiş taranmış PDF dosyası.',
          fillStrategy: 'MANUAL_UPLOAD',
          rules: { isMandatory: true },
          guidance: {
            school: 'Sistemden DoH şablonunu indirin, Okul Müdürünüze imzalatıp mühürletin ve PDF formatında sisteme yükleyin.',
            host: 'Ev sahibi kurum bu belgeyi imzalamaz; belge yalnızca başvuran okulu bağlar.',
          },
        },
      ],
    },
    {
      id: 'application-conditions',
      pageNumber: 19,
      title: 'Application conditions & Checklists',
      description: 'AB değerleri, yaptırım kontrolleri, ÖZGÜN İÇERİK BEYANI (ücretli harici danışmanlık yasağı) ve başvuru öncesi kontrol listesi.',
      fields: [
        {
          id: 'cond_eu_values_adhere',
          fieldCode: 'EU Values adherence',
          label: 'I confirm that I, my organisation and the co-beneficiaries (where applicable) adhere to the EU values mentioned in Article 2 of the TEU and Article 21 of the EU Charter of Fundamental Rights',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'İnsan onuru, özgürlük, eşitlik ve insan hakları ilkelerine bağlılık onayı.', host: 'Zorunlu taahhüt.' },
        },
        {
          id: 'cond_eu_values_eval',
          fieldCode: 'EU Values evaluation criteria',
          label: 'I understand and agree that EU Values will be used as part of the criteria for evaluation of the activities implemented under this project',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Zorunlu onay kutusu.', host: 'Zorunlu taahhüt.' },
        },
        {
          id: 'cond_sanctions_check',
          fieldCode: 'EU sanctions compliance',
          label: 'I confirm that I/my organisation/project partner are NOT included on the list of persons/entities subject to EU sanctions',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Kurumun ve ortakların AB yaptırım listesinde olmadığını onaylar.', host: 'AB yaptırımlarına tabi olunmadığı beyanı.' },
        },
        {
          id: 'cond_russia_restriction',
          fieldCode: 'Russia restrictive measures',
          label: 'I/my organisation/project partner are not established in Russia nor are any of our proprietary rights directly or indirectly owned for more than 50% by a legal person, entity or body established in Russia',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Zorunlu yasal onay.', host: 'Zorunlu yasal onay.' },
        },
        {
          id: 'cond_audit_consent',
          fieldCode: 'Audit and monitoring consent',
          label: 'I/my organisation consent and acknowledge that information concerning me/my organisation, application and assessments can be made accessible to authorised persons of the EC, EACEA and National Agencies',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Denetim ve izleme yetkisinin kabulü.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'cond_original_content',
          fieldCode: 'Original content confirmation',
          label: 'I confirm that this application contains original content authored by the applicant organisation.',
          description: 'Başvurunun başvuru sahibi kurum tarafından özgün olarak kaleme alındığının teyidi.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: '⚠️ ÇOK KRİTİK KA122 ŞARTI: Başvuru metinleri okulun kendi öğretmenleri tarafından hazırlanmış olmalıdır. Mobility Nexus gibi kurum içi yapay zeka asistanları okulun kendi rehberliğinde çalıştığı için tam uyumludur.',
            host: 'İşlem gerekmez.',
          },
        },
        {
          id: 'cond_no_paid_external_drafting',
          fieldCode: 'No paid external drafting',
          label: 'I confirm that no other organisations or individuals external to the applicant organisation have been paid or otherwise compensated for drafting the application.',
          description: 'Başvuruyu yazdırmak için kurum dışından hiçbir harici şahıs veya danışmanlık firmasına ücret ÖDENMEDİĞİNİN resmi beyanı.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: {
            school: '⚠️ DİKKAT: Avrupa Komisyonu piyasadaki ticari proje yazıcı taşeron firmaları kesin olarak yasaklamıştır! Bu kutucuğun işaretlenmesi yasal bir taahhüttür; harici firmaya para ödendiği tespit edilirse başvuru doğrudan iptal edilir ve hibe kesilir.',
            host: 'Host kurumlar kesinlikle "proje yazma parası" talep etmemelidir; sadece staj ve eğitim ortağı olarak görev almalıdır.',
          },
        },
        {
          id: 'cond_data_sharing_eacea',
          fieldCode: 'Information sharing across EC, EACEA and NAs',
          label: 'I acknowledge that information concerning me/my organisation/project partners, the application and the related capacity assessment... can be made accessible to and shared between the European Commission, EACEA and the National Agencies for Programme implementation purposes.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Zorunlu onay.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'chk_eligibility',
          fieldCode: 'Eligibility criteria fulfilled',
          label: 'It fulfills the eligibility criteria listed in the Programme Guide.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Uygunluk kriterleri teyidi.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'chk_fields_completed',
          fieldCode: 'All fields completed',
          label: 'All relevant fields in the application form have been completed.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'Tüm alanların eksiksiz doldurulduğu kontrolü.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'chk_correct_na',
          fieldCode: 'Correct National Agency chosen',
          label: 'You have chosen the correct National Agency of the country in which your organisation is established.',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'TR01 - Türkiye Ulusal Ajansı teyidi.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'chk_correct_field',
          fieldCode: 'Correct field chosen',
          label: 'You have chosen the correct field for your organisation. Currently, the selected field is: Vocational Education and Training',
          fillStrategy: 'DECLARATION',
          rules: { isMandatory: true },
          guidance: { school: 'VET (Mesleki Eğitim) alanı teyidi.', host: 'İşlem gerekmez.' },
        },
      ],
    },
    {
      id: 'submission-history',
      pageNumber: 21,
      title: 'Submission history',
      description: 'Formun Avrupa Komisyonu resmi portalına gönderim kayıtları.',
      fields: [
        {
          id: 'sub_version',
          fieldCode: 'Version',
          label: 'Submission Version',
          description: 'Başvuru versiyon numarası (Örn: v1, v2).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: { school: 'Komisyon sunucusu tarafından atanır.', host: 'İşlem gerekmez.' },
        },
        {
          id: 'sub_time',
          fieldCode: 'Submission time (Brussels time)',
          label: 'Submission time (Brussels time)',
          description: 'Resmi Brüksel saati ile gönderim zaman damgası.',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Son başvuru saatinden (genellikle Brüksel saatiyle 12:00) önce gönderildiğinin yasal kanıtıdır.',
            host: 'İşlem gerekmez.',
          },
        },
        {
          id: 'sub_id',
          fieldCode: 'Submission ID',
          label: 'Submission ID',
          description: 'Avrupa Komisyonu resmi gönderim onay kodu (Submission Hash / ID).',
          fillStrategy: 'SYSTEM_GENERATED',
          rules: { isMandatory: true },
          guidance: {
            school: 'Başvurunun başarıyla sisteme ulaştığını kanıtlayan referans numarasıdır; arşivde saklanmalıdır.',
            host: 'İşlem gerekmez.',
          },
        },
      ],
    },
  ],
};
